### ISSUE TITLE
manage profile - not all languages in list

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#10]
it stops at Portuguese

<img width="584" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/83a6ac27-ef39-4bf1-bda2-5c88b7f423a7">

without showing Punjabi, Russian, etc.

<img width="356" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/9bedbb53-1e62-48a4-9f82-81e793817bdc">

**Comment by thedoctor27** [comment]
fixed
