### ISSUE TITLE
manage profile - not all countries in list

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#11]
it stops at india

<img width="584" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/9fec2542-ebe8-4e5e-8621-7dbe5a86dd9a">

not showing many other countries

<img width="449" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/2fbe0d48-0b89-4f80-bc7a-a36c1aa638b9">

**Comment by thedoctor27** [comment]
fixed
