### ISSUE TITLE
search - last approved users not shown

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#14]
show test users disabled

real user approved

<img width="322" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/b33c1211-f44f-4654-a6a3-3f260b2fe1ce">

<img width="900" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/3c0e61c5-0fd3-4afc-8731-a1e8fc109269">

**Comment by thedoctor27** [comment]
don't understand the issue,
the search is empty because you didn't select any option,

**Comment by zen37** [comment]
sorry, my fault I wasn't clear, it should have been on home page (let's say half of it, right)

"displaying LAST_REGISTERED_APPROVED_COUNT = 20 registered and approved users that have a photo if there are not 20 users with photo, users without will be displayed too but at the end."

**Comment by thedoctor27** [comment]
fixed

**Comment by zen37** [comment]
![image](https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/746734a6-f079-4493-851d-d663671f1258)

test101 is approved but not showing on Home page

![image](https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/ace9ac6a-4522-4a63-a413-247397647c2a)

**Comment by thedoctor27** [comment]
ah so you want to display the last 20 registered and approved in public home page with out login ?

**Comment by thedoctor27** [comment]
fixed
