### ISSUE TITLE
question - initial queries

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#15]
search page displayed, no search criteria entered, no search performed

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3,200ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT CONVERT(varchar(11), [t].[IdCountry])
      ........
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2,738ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ....

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2,284ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
     ....
      
     These queries load everything in the db.
     
     **Is this best practices to load everything at the beginning when the user goes to Search?** 
     
     It takes 9 sec. now for 11,000 users. What if there would be 100k users ?

**Comment by zen37** [comment]
front loading the data does not seem to yield any performance benefits as when search criteria is entered, the db is hit again

<img width="899" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/e4792f76-471d-4908-b248-32dc376af4ee">

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
.......
.......
      
  
<img width="878" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/765266d9-2de9-4648-8fb5-32a21b3d1a93">

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (7,708ms) [Parameters=[@__model_IdCountry_0='?' (DbType = Int32), .
      .....

**Comment by zen37** [comment]
it seems the initial queries (no search criteria entered) are only for creating the drop-down lists.

wouldn't it be more efficient to have something like 

`SELECT distinct [u].[IdCountry], [u].[Test]FROM [UserProfiles] AS [u]`

and the same for the other lists, no need to retrieve all records, unless I'm missing something

**Comment by thedoctor27** [comment]
i fixed the entityframwork query,
if the performance issue still exist, i'll just write raw query
