### ISSUE TITLE
search - countries and languages in the list for test users

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#16]
test users mode: disabled

<img width="275" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/767f48de-2caa-40b1-aeb4-0112ed233465">

<img width="348" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/a131f0aa-35d4-47c2-a779-5ef9d737dd1e">

only France and French should be in lists

<img width="290" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/9517d063-374d-4058-864a-6593d1b32623">

<img width="186" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/d93d2cb2-ec52-4c7e-aa8d-4706c0385f68">

**Comment by thedoctor27** [comment]
fixed
