### ISSUE TITLE
search - languages list opens up instead of down

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#17]
user cannot see the other languages to select

<img width="293" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/3372d907-9285-446f-a1de-f41575c40da2">

for countries there is not such an issue
<img width="248" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/8b3059a1-c0ef-4931-8318-2b9a0c1a61e6">

**Comment by thedoctor27** [comment]
can't do anything about that, that option is set automaticly depending on the user screen
the only thing i can do, is to set the max height of the list

**Comment by zen37** [comment]
so why is Countries list properly opening up? user screen is the same

**Comment by thedoctor27** [comment]
![image](https://github.com/thedoctor27/Zen33-Activities-SLN/assets/19738229/b2edec13-2572-48e5-99af-dd3736bebc2a)
this is  a screen releted issue and i can't change it,
this param is set by mudblazor depending on the screen size, 
as you can see in my screen i don't have this issue
