### ISSUE TITLE
search - countries list not loaded until languages and activities not retrieved

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#18]
confusing for the user as the list is empty, bun then it gets filled; noticed that until languages and activities are read from the db, the countries list won't show up

<img width="638" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/5cd5fea6-2fc4-43a7-ab99-849e07d88092">

the display of each list should be independent of each other

**Comment by thedoctor27** [comment]
i added a loading progress,
keep in mind that after i fixed the query, initial loading won't take long time now
