### ISSUE TITLE
search - around 11 sec. to select country in the list (revisit)

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#19]
around 11 sec

<img width="337" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/d8b0fe46-a00b-4c91-937f-6b272825abcc">

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (11,341ms).....
      
<img width="296" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/253f2e6e-93e4-4d75-9e48-a590eee20e49">

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (10,998ms)....

**Comment by thedoctor27** [comment]
how many users did you add to cause that delay issue ?

**Comment by thedoctor27** [comment]
should be fixed now, after i changed the query syntax

**Comment by zen37** [comment]
still same

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (7,157ms) [Parameters=[@__idCOuntry_0='?' ......

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (6,116ms) [Parameters=[@__idCOuntry_0='?' ......
      
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (9,024ms) [Parameters=[@__idCOuntry_0='?' ......
      
still takes time, it is because of having to get the languages also for the selected country first

**Comment by zen37** [comment]
leaving it open for now to come back to it later

**Comment by thedoctor27** [comment]
fixed
