### ISSUE TITLE
not all countries in the search list

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#2]
<img width="493" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/7ea11669-5290-422e-98c8-e231ba558be5">

**it cuts off at Italy**

<img width="763" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/6d510116-9463-4f02-ada7-f494f922b8bf">

**Comment by thedoctor27** [comment]
fixed
