### ISSUE TITLE
search: all languages in the result list despite having selected a specific language

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#21]
select language and search
<img width="890" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/dc988d9c-f1a4-4c69-be83-31b6c03cc7af">

select country
<img width="888" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/f8f742c1-17ee-4ca4-ae97-c6a1e6eb3fbe">

**Comment by thedoctor27** [comment]
fixed, now i initialise the language field if the country change
