### ISSUE TITLE
profile stays approved after user changed it

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#25]
user changes an attribute and the profile does not go automatically to 'Under review' as it should

users changed their language to Arabic
![image](https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/60fdc02e-99a7-48e4-a0e5-2206c1d3eb7c)

didn't test for all attributes, but I suppose it is the same issue

**Comment by thedoctor27** [comment]
fixed
