### ISSUE TITLE
search: non-approved profiles are displayed for non-admin roles

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#26]
non-approved profiles (for example all of them in the screenshot) are displayed, the idea behind the approval process is that offensive profiles not to be visible for users, now they could see them if there are any

![image](https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/9f99ec21-5403-4d58-905a-1c8334e8c38b)

**Comment by thedoctor27** [comment]
fixed

**Comment by zen37** [comment]
first search only approved profiles displayed
<img width="1278" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/1adf3a82-5604-4b21-9159-0a4293b379b5">
press Clear
<img width="406" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/03fa84e7-5f2b-464f-8c99-1c7a60c320d5">
Choose country and search again, non-approved profiles are shown
<img width="1275" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/43c2d798-ad9f-46de-a340-fd296d60c284">

**Comment by zen37** [comment]
Deployment of the fix won't affect the database, will it? 
I'd like the data to be kept, took some time to add some 20k test users :)

**Comment by thedoctor27** [comment]
yes deployment won't affect database

**Comment by thedoctor27** [comment]
fixed
