### ISSUE TITLE
home: test users are shown too, even if test mode is not enabled

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#28]
![image](https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/d1bc0ed2-c1e0-44a9-b34c-3e54f58a0dda)

![image](https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/653f0404-82ab-4b80-b891-a9d03dbc7231)

**Comment by thedoctor27** [comment]
fixed
