### ISSUE TITLE
not all languages in search list

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#3]
<img width="903" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/cdbd6f19-ff15-4967-b684-6609be971e90">

**for example Arabic, Chinese are missing**

<img width="800" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/9c2ff0cb-c2fd-43fb-ac36-deef3f043a01">

**Comment by thedoctor27** [comment]
did you select a country before opening that list ?

**Comment by zen37** [comment]
yes

<img width="899" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/a34b869a-2a2c-4308-b1b6-c175300f8219">

only 7 languages in the list

<img width="323" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/8e97abcd-a047-449b-a4e2-3bc0376200f9">

even if db has 11

<img width="663" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/7177c438-8b4e-4caf-a96d-6ad7381abcb5">

**Comment by thedoctor27** [comment]
unselect the country and you will see all the languages,

same filter is applied when you choose the language first, in that case the list of countries will be filtred

**Comment by thedoctor27** [comment]
i pushed a fix,

**Comment by thedoctor27** [comment]
fixed
