### ISSUE TITLE
home: last approved profile not shown

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#30]
last approved profile

<img width="1213" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/1bec4243-8504-497a-a18f-b9b9177572cf">

does not show up on home page

<img width="1045" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/a6aa44e7-ae41-43a5-9803-5ba94e91b741">

<img width="1141" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/021bd1f0-f34f-48cb-943c-ce44dc01857b">

**Comment by thedoctor27** [comment]
fixed,
