### ISSUE TITLE
Log in for non-admin user: NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#5]
if the user is non-admin

<img width="533" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/a291bd96-76a0-41df-9f7a-b18df9122f37">

<img width="875" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/c3446490-4d31-46bf-a0df-5f111dab02b1">

**Comment by thedoctor27** [comment]
changes pushed
