### ISSUE TITLE
list of countries not available once a country has been selected

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#6]
<img width="331" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/4f5d54b6-5937-4687-b8d6-2c52110c8ab8">

dropdown list should be still available in case the user wants to change the selection

**Comment by thedoctor27** [comment]
you can delete that word and be able to see the list, 
it's mudblazor autocomplete componenet default befahvior

**Comment by thedoctor27** [comment]
fixed
