### ISSUE TITLE
Profile not standard

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#7]
Shouldn't Profile be back to standard as we have 'Manage Profile' for all custom fields?
https://localhost:7290/Identity/Account/Manage 

<img width="886" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/6ab8e887-4eec-4839-8363-63fcad426ea4">

**Comment by thedoctor27** [comment]
as you like, it's up to you

**Comment by thedoctor27** [comment]
i can clear it, there is no reason to put the same fonctionnality in two places

**Comment by thedoctor27** [comment]
fixed
