### ISSUE TITLE
test users displayed even if test mode is not set 

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#8]
no users as expected
<img width="931" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/a8901866-8cc5-4029-a0d3-e9c63bc9bd08">

next country, test users are displayed

<img width="894" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/5cb58843-b7c1-48a8-b4e2-642fdae0f111">

back to first country, test users are displayed now

<img width="884" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/212052f6-9d07-4c40-88e2-ca8e8a6ed6e9">

**Comment by thedoctor27** [comment]
i wasn't able to reproduce that issue in my env

**Comment by thedoctor27** [comment]
this error, occures when you use the clear botton,

the testUser variable is not set,

it fixed now
