### ISSUE TITLE
manage profile, some attributes cannot be changed

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#9]
those that are in lists

<img width="645" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/210033ee-75b4-48e9-93b8-a8a7af674c67">

<img width="438" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/b8f687d6-997a-4e6b-8596-903b3744cd5d">

**Comment by thedoctor27** [comment]
just delete the text, it's the default behavior of the mudblazor autocomplete

**Comment by thedoctor27** [comment]
this one is fixed, now
